#!/usr/bin/env python3
"""export_onnx.py — export a trained model to ONNX and write the
controller's schema-v1 model manifest next to it.

The manifest is the contract consumed by controller/src/manifest.rs
(validate with `controller.exe --manifest-check <manifest.json>`).
Labels order MUST match the class indices used in annotation; the
export fails loudly on any mismatch instead of guessing.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("weights", help="trained .pt weights (kept out of Git)")
    p.add_argument("--name", required=True, help="model name for the manifest")
    p.add_argument("--version", default="0.1.0", help="model version for the manifest")
    p.add_argument("--game-profile", default="generic-ui", help="game/profile tag (default: generic-ui)")
    p.add_argument("--labels", required=True,
                   help="comma-separated class names, index-ordered (e.g. 'button_green,dialog')")
    p.add_argument("--imgsz", type=int, default=640, help="export imgsz (default: 640)")
    p.add_argument("--confidence", type=float, default=0.6, help="default_confidence in (0,1] (default: 0.6)")
    p.add_argument("--opset", type=int, default=13, help="ONNX opset (default: 13)")
    p.add_argument("--out-dir", default="dist/models", help="export directory (default: dist/models)")
    p.add_argument("--yes", action="store_true", help="actually run (requires ultralytics)")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    labels = [s.strip() for s in args.labels.split(",") if s.strip()]
    if not labels:
        print("export_onnx: ERROR --labels must name at least one class", file=sys.stderr)
        return 2
    if not (0.0 < args.confidence <= 1.0):
        print("export_onnx: ERROR --confidence must be in (0, 1]", file=sys.stderr)
        return 2
    if not (0 < args.imgsz <= 4096):
        print("export_onnx: ERROR --imgsz must be in 1..=4096", file=sys.stderr)
        return 2
    weights = Path(args.weights)
    if not weights.is_file():
        print(f"export_onnx: ERROR weights not found: {weights}", file=sys.stderr)
        return 2

    out_dir = Path(args.out_dir)
    stem = weights.stem
    onnx_path = out_dir / f"{stem}.onnx"
    manifest_path = out_dir / f"{stem}.manifest.json"
    print("export_onnx: PLAN " + json.dumps({
        "weights": str(weights.resolve()),
        "onnx": str(onnx_path),
        "manifest": str(manifest_path),
        "imgsz": args.imgsz,
        "opset": args.opset,
        "labels": labels,
    }, indent=2))
    if not args.yes:
        print("export_onnx: dry plan only — pass --yes to execute")
        return 0

    if importlib.util.find_spec("ultralytics") is None:
        print("export_onnx: ERROR ultralytics is not installed; refusing to auto-install",
              file=sys.stderr)
        return 2

    from ultralytics import YOLO  # imported only after the gate

    model = YOLO(str(weights))
    exported = model.export(format="onnx", imgsz=args.imgsz, opset=args.opset)
    exported_path = Path(exported)
    out_dir.mkdir(parents=True, exist_ok=True)
    if exported_path != onnx_path:
        exported_path.replace(onnx_path)

    manifest = {
        "schema_version": 1,
        "name": args.name,
        "version": args.version,
        "game_profile": args.game_profile,
        "input_size": {"width": args.imgsz, "height": args.imgsz},
        "labels": labels,
        "default_confidence": args.confidence,
        "weights": onnx_path.name,
        "notes": "Generated by tools/vision/export_onnx.py; weights stay external to Git.",
    }
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"export_onnx: wrote {onnx_path}")
    print(f"export_onnx: wrote {manifest_path}")
    print("export_onnx: validate with: controller.exe --manifest-check "
          f"{manifest_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
