//! Shared fixture for the ONNX runtime tests: a tiny constant-output ONNX
//! model, hand-encoded as protobuf (no Python, no onnx toolchain, no
//! downloads — ROADMAP §4 keeps heavy tooling out of the runtime). The
//! model exercises the REAL WinML path (load → session → bind → evaluate
//! → tensor parse) while its weights stay a few hundred bytes.
//!
//! Graph contract:
//! - input  `images` FLOAT [1,3,64,64] (declared, deliberately unused —
//!   the detection rows are constant, which makes the decode test exact)
//! - output `output` FLOAT [1,2,6], rows (cx, cy, w, h, conf, class):
//!   row 0 = [32, 16, 20, 10, 0.9, 0]  → survives a 0.6 confidence gate
//!   row 1 = [16, 48,  8,  8, 0.4, 1]  → filtered at 0.6, visible at 0.3

use std::path::{Path, PathBuf};

pub fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

pub fn manifest_path() -> PathBuf {
    fixtures_dir().join("constant_yolo.manifest.json")
}

pub fn weights_path() -> PathBuf {
    fixtures_dir().join("constant_yolo.onnx")
}

/// Second fixture: YOLOv8-style CHANNELS-FIRST output `[1, 6, 2]`
/// (C = 4 + 2 classes, N = 2 columns), exercising the auto-detect path:
///
/// - col 0: cx=20 cy=20 w=10 h=10, score_a=0.95, score_b=0.05 → rect_a
/// - col 1: cx=40 cy=40 w=10 h=10, score_a=0.60, score_b=0.70 → rect_b
pub fn v8_manifest_path() -> PathBuf {
    fixtures_dir().join("constant_yolo_v8style.manifest.json")
}

pub fn v8_weights_path() -> PathBuf {
    fixtures_dir().join("constant_yolo_v8style.onnx")
}

pub const V8_MANIFEST_JSON: &str = r#"{
    "schema_version": 1,
    "name": "constant-yolo-v8style-fixture",
    "version": "0.1.0",
    "game_profile": "generic-ui",
    "input_size": { "width": 64, "height": 64 },
    "labels": ["rect_a", "rect_b"],
    "default_confidence": 0.6,
    "weights": "constant_yolo_v8style.onnx",
    "notes": "Channels-first [1,4+nc,N] constant-output fixture generated by tests/common/mod.rs."
}"#;

pub fn ensure_v8_fixture() -> (PathBuf, PathBuf) {
    std::fs::create_dir_all(fixtures_dir()).expect("fixtures dir");
    ensure_file(&v8_weights_path(), &build_v8style_onnx_bytes());
    ensure_file(&v8_manifest_path(), V8_MANIFEST_JSON.as_bytes());
    (v8_manifest_path(), v8_weights_path())
}

pub const MANIFEST_JSON: &str = r#"{
    "schema_version": 1,
    "name": "constant-yolo-fixture",
    "version": "0.1.0",
    "game_profile": "generic-ui",
    "input_size": { "width": 64, "height": 64 },
    "labels": ["rect_a", "rect_b"],
    "default_confidence": 0.6,
    "weights": "constant_yolo.onnx",
    "notes": "Constant-output ONNX fixture generated by tests/common/mod.rs; exercises the real WinML path without any heavy tooling."
}"#;

/// Write the fixture files if missing; returns (manifest, weights) paths.
/// Concurrent cargo test binaries may race here, so writes go to a
/// temp file and are moved into place (last writer wins; content is
/// deterministic, so any winner produces the same bytes).
pub fn ensure_fixture() -> (PathBuf, PathBuf) {
    std::fs::create_dir_all(fixtures_dir()).expect("fixtures dir");
    ensure_file(&weights_path(), &build_onnx_bytes());
    ensure_file(&manifest_path(), MANIFEST_JSON.as_bytes());
    (manifest_path(), weights_path())
}

fn ensure_file(target: &Path, bytes: &[u8]) {
    if target.exists() {
        return;
    }
    let tmp = target.with_extension(format!("tmp.{}", std::process::id()));
    if std::fs::write(&tmp, bytes).is_ok() {
        let _ = std::fs::rename(&tmp, target);
    }
}

// --- minimal protobuf encoding (proto3 wire format) ---

fn push_varint(mut v: u64, out: &mut Vec<u8>) {
    loop {
        let b = (v & 0x7f) as u8;
        v >>= 7;
        if v == 0 {
            out.push(b);
            return;
        }
        out.push(b | 0x80);
    }
}

fn push_tag(field: u32, wire: u32, out: &mut Vec<u8>) {
    push_varint(((field << 3) | wire) as u64, out);
}

fn push_len_delim(field: u32, payload: &[u8], out: &mut Vec<u8>) {
    push_tag(field, 2, out);
    push_varint(payload.len() as u64, out);
    out.extend_from_slice(payload);
}

fn push_varint_field(field: u32, v: i64, out: &mut Vec<u8>) {
    push_tag(field, 0, out);
    push_varint(v as u64, out);
}

fn push_str_field(field: u32, s: &str, out: &mut Vec<u8>) {
    push_len_delim(field, s.as_bytes(), out);
}

fn push_floats(field: u32, vals: &[f32], out: &mut Vec<u8>) {
    push_tag(field, 2, out);
    push_varint((vals.len() * 4) as u64, out);
    for v in vals {
        out.extend_from_slice(&v.to_le_bytes());
    }
}

/// ValueInfoProto for a FLOAT tensor with `dims`:
/// `ValueInfoProto { name=1, type=2 }` → `TypeProto { tensor_type=1 }` →
/// `Tensor { elem_type=1: FLOAT, shape=2 }` → `TensorShapeProto.dim`.
fn value_info(name: &str, dims: &[i64]) -> Vec<u8> {
    let mut vi = Vec::new();
    push_str_field(1, name, &mut vi);
    let mut tensor_msg = Vec::new();
    push_varint_field(1, 1, &mut tensor_msg); // Tensor.elem_type = FLOAT
    let mut shape = Vec::new();
    for &d in dims {
        let mut dim = Vec::new();
        push_varint_field(1, d, &mut dim);
        push_len_delim(1, &dim, &mut shape);
    }
    push_len_delim(2, &shape, &mut tensor_msg); // Tensor.shape
    let mut type_proto = Vec::new();
    push_len_delim(1, &tensor_msg, &mut type_proto); // TypeProto.tensor_type
    push_len_delim(2, &type_proto, &mut vi); // ValueInfoProto.type
    vi
}

fn build_onnx_bytes() -> Vec<u8> {
    // initializer "out": FLOAT[1,2,6] with the two constant rows
    let rows: [f32; 12] = [
        32.0, 16.0, 20.0, 10.0, 0.9, 0.0, //
        16.0, 48.0, 8.0, 8.0, 0.4, 1.0,
    ];
    model_with_constant_output("constant_yolo_fixture", &[1, 2, 6], &rows)
}

fn build_v8style_onnx_bytes() -> Vec<u8> {
    // initializer "out": FLOAT[1,6,2], channels-first (cx, cy, w, h,
    // score_a, score_b) × 2 columns
    let cols: [f32; 12] = [
        20.0, 40.0, // cx
        20.0, 40.0, // cy
        10.0, 10.0, // w
        10.0, 10.0, // h
        0.95, 0.60, // score rect_a
        0.05, 0.70, // score rect_b
    ];
    model_with_constant_output("constant_yolo_v8style_fixture", &[1, 6, 2], &cols)
}

/// Hand-rolled ModelProto: input `images` [1,3,64,64] (unused), output
/// `output` = Identity(constant FLOAT`out_dims` = `data`).
fn model_with_constant_output(graph_name: &str, out_dims: &[i64], data: &[f32]) -> Vec<u8> {
    let mut init = Vec::new();
    push_tag(1, 2, &mut init);
    push_varint(out_dims.len() as u64, &mut init);
    for d in out_dims {
        push_varint(*d as u64, &mut init);
    }
    push_varint_field(2, 1, &mut init); // data_type FLOAT
    push_floats(4, data, &mut init);
    push_str_field(8, "out", &mut init);

    // node: Identity("out") -> "output"
    let mut node = Vec::new();
    push_str_field(1, "out", &mut node);
    push_str_field(2, "output", &mut node);
    push_str_field(4, "Identity", &mut node);

    let mut graph = Vec::new();
    push_len_delim(1, &node, &mut graph);
    push_str_field(2, graph_name, &mut graph);
    push_len_delim(5, &init, &mut graph);
    // declared (unused) input + the output
    push_len_delim(11, &value_info("images", &[1, 3, 64, 64]), &mut graph);
    push_len_delim(12, &value_info("output", out_dims), &mut graph);

    let mut model = Vec::new();
    push_varint_field(1, 3, &mut model); // ir_version 3: oldest IR every WinML/ORT accepts
    push_len_delim(7, &graph, &mut model);
    let mut opset = Vec::new();
    push_varint_field(2, 9, &mut opset); // opset 9: Win10 1809-era WinML floor (Identity@9, ir3)
    push_len_delim(8, &opset, &mut model);
    model
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_bytes_parse_back_as_the_declared_model() {
        // sanity: the hand-rolled protobuf is at least self-consistent in
        // size (model > graph > node/init) and the fixture round-trips
        // through the controller manifest parser
        let bytes = build_onnx_bytes();
        assert!(
            bytes.len() > 100 && bytes.len() < 4096,
            "{} bytes",
            bytes.len()
        );
        assert_eq!(bytes[0], 0x08, "field 1 varint (ir_version) first");
        let m = controller::manifest::parse_json(MANIFEST_JSON).expect("manifest");
        assert_eq!(m.imgsz(), (64, 64));
        assert_eq!(m.labels, vec!["rect_a", "rect_b"]);
    }
}
